// <auto-generated />
namespace BrambleWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BrambleModelsDataModelsApiModelsMusicBrainzModelsMusicBrainzGenreModelscs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrambleModelsDataModelsApiModelsMusicBrainzModelsMusicBrainzGenreModelscs));
        
        string IMigrationMetadata.Id
        {
            get { return "202312082014531_Bramble.Models.DataModels.ApiModels.MusicBrainzModels.MusicBrainzGenreModels.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
